#!/bin/sh

case "$1" in
  start)
        echo "Start erasing ..."                  
	echo -e "\a"
        ;;
  stop)   
        ;;       
  restart|reload)
        ;;
  *)                                         
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
